### ISSUE TITLE
New release, version 0.4 or 1.0 or something else?

### ISSUE THREAD

**Issue by chriscool** [chriscool/sharness#44]
It looks like there has been no release since v0.3.0 in April 2013.
As there has been some significant changes since that time, it would be nice to create a new release.

What should it be called? 0.4.0? 1.0?

As sharness is quite stable, I think we should aim for 1.0, but perhaps there are things that people would like for a 1.0?
Should we get rid of README.git for example?

**Comment by mlafeldt** [comment]
We definitely need a new release with all the changes. I'm fine with aiming for 1.0.

Merging `README.git` with our `README` or creating a Wiki has been something I never came around to. While it's a good idea in general, I'm not sure whether it's a blocker for 1.0.

**Comment by chriscool** [comment]
About a Wiki, did you think about a GitHub wiki or something else?
Anyway yeah let's plan to make a 1.0 release soon.

**Comment by mlafeldt** [comment]
No, nothing in particular. In fact, I don't like separating code from documentation. So forget about the wiki thing. :)

**Comment by chriscool** [comment]
Ok, I will take a look at `README.git` and anyway make a 1.0 release next week or maybe the week after.

**Comment by chriscool** [comment]
Ok, i am very late but here is what I came up with for the Release Notes:

```
Release Notes for version v1.0.0
================================

These notes describe changes since the previous v0.3.0 version from
April 3 2013.

The new v1.0.0 version contains both many upstream fixes and
improvements from Git and a lot of specific user contributed features.

We think that Sharness is used and supported by enough projects and
developers, and stable enough, now to be ready for a v1.0.0 version.


Externally visible features
---------------------------

- Add a 'cleanup' api to register cleanup actions, thanks to Dennis
  Kaarsemaker.

- Add simple test_seq(), thanks to Christian Couder.

- Add test_pause() from Git, thanks to Christian Couder.

- Add test_must_be_empty(), thanks to Konstantin Koroviev.

- Add SHARNESS_TEST_SRCDIR to run tests from a different directory,
  thanks to Mark A. Grondona.

- Implement --long-tests to run EXPENSIVE tests, thanks to Matthieu
  Moy.

- Support extensions in a sharness.d directory, thanks to Mark
  A. Grondona.

- Interactive tests, thanks to Dennis Kaarsemaker.


Internal improvements and bug fixes
-----------------------------------

- Add a linter that detects broken && chains, thanks to Dennis
  Kaarsemaker.

- Export SHELL_PATH, thanks to Christian Couder.

- Fix color support when tput needs ~/.terminfo, thanks to Richard
  Hansen.

- Fix pathname of test-results/*.counts file, thanks to Richard
  Hansen.

- Sort test scripts before running them, thanks to Richard Hansen.

- Use SHARNESS_TRASH_DIRECTORY to enter the trash directory and drop
  the test_dir internal variable, thanks to Alexander Sulfrian.

- A lot of new TTY and sub sharness related tests, thanks to Mark
  A. Grondona.

- Build on Travis-CI using a container based build infrastructure,
  thanks to Mark A. Grondona.


Documentation improvements
--------------------------

- Mention the Sharness Cookbook in the README, thanks to Mathias
  Lafeldt.

- Add alternatives to Sharness like Cram, rnt and ts to the README,
  thanks to Roman Neuhauser and Simon Chiang.

- Consistent Markdown headings, thanks to Mathias Lafeldt.

- Replace Contact with Author section, thanks to Mathias Lafeldt.

- New CONTRIBUTING.md document, thanks to Christian Couder.

- Mention Sharnessify a new installation tool, thanks to
  Christian Couder.

- Usage clarifications, thanks to Matthieu Moy.

- Improved flag descriptions in the README, thanks to Matthieu Moy.
```

**Comment by chriscool** [comment]
I am not very happy with the CHANGELOG.md. I'd prefer a "release_notes" or "changelog" directory where we would put the release notes, one file per release.

The reason is that I would like to send an announcement on the Git mailing list, and maybe perhaps elsewhere like the IPFS users mailing list, and it's better to point to or just attach the release notes than to point to or attach the full CHANGELOG.md.

**Comment by moy** [comment]
One option is to have a CHANGELOG.md and cut&paste the relevant section to a GitHub release. Then you can point users directly to the GitHub release.

**Comment by chriscool** [comment]
@moy ok I will try that. I will add the above release text to https://github.com/mlafeldt/sharness/blob/master/CHANGELOG.md while trying to not change much its format and send a PR.

**Comment by chriscool** [comment]
v1.0.0 is released, so this can be closed.
