### ISSUE TITLE
test_cmp doesn't work with parameters containing spaces 

### ISSUE THREAD

**Issue by Kubuxu** [chriscool/sharness#56]
Example reproduce: https://gist.github.com/Kubuxu/6c718fd3756a765aaba3e079ad5f5814

The `test_cmp` seems to expand arguments on spaces.

This might be problem with `"$@"` expansion in case of bash functions but I might be doing something wrong too.

The problem arises because sharness itself uses space for `trash directory` name. Allowing to override this name/change default would decrease severity significantly, if the bug itself is hard to fix.

**Comment by johnkeeping** [comment]
The problem is in the line:

    DIR="$(dirname $(realpath somefile))" && 

you can see this if you add `set -x` to the top of the test case, it shows:

    ++ DIR='/home/john/external/src/sharness/test
    directory.simple'

The corrected line adds quotes around the argument to `dirname`:

    DIR="$(dirname "$(realpath somefile)")" &&

**Comment by Kubuxu** [comment]
You are right, thanks/

The initial issue is still present in my test (go-ipfs), let me check for better replication.

**Comment by Kubuxu** [comment]
Ahh, the problem isn't in the test_cmp itself. The problem is when the files are different and `test_fsh` tries to show the reason.

**Comment by Kubuxu** [comment]
Sorry, looks like someone did override `test_cmp` in our framework, and I didn't know about it. As I tried to replicate it I made a mistake.

Thanks for your input.
