### ISSUE TITLE
make test fails with unliked SHELL_PATH

### ISSUE THREAD

**Issue by chu11** [chriscool/sharness#58]
Cloned the master repo and did a ```make test``` just to try things out and saw failures all over the place.  After digging, it's because the tests in ```sharness.t``` did not like my default shell, which is set into the generated test scripts in ```run_sub_test_lib_test()``` via the environment variable ```SHELL_PATH``` (set in ```sharness.sh``` via ```SHELL```).

Since a number of tests in ```sharness.t``` assume bourne shell, perhaps it should be set as such?

```diff
@@ -50,7 +50,7 @@ run_sub_test_lib_test () {
        (
                cd "$name" &&
                cat >".$name.t" <<-EOF &&
-               #!$SHELL_PATH
+               #!/bin/sh
 
                test_description='$descr (run in sub sharness)
```

Can send a PR, just wanted to ping first.

**Comment by chriscool** [comment]
@chu11 thank you for this issue.

I think it should work if you use `make SHELL_PATH=/bin/sh test` instead of `make test`.
It is also more flexible to not hardcode `/bin/sh`. And on some platform `/bin/sh` might be too old or not as feature complete as we need.

What could be done is to detect when the current shell is not appropriate and if that is the case to suggest using something like `make SHELL_PATH=/bin/sh test` instead of `make test`.

**Comment by chu11** [comment]
@chriscool That seems like a good idea, to simply just warn the user if bourne shell isn't used.  I think the main issue for me was just seeing tons of failures of 'make test' and not sure what to make of it.

**Comment by anarcat** [comment]
which shell *does* sharness depend on anyways? sh or bash?

**Comment by chriscool** [comment]
Sharness should work with most sh compatible shells. There are no strict rules, but there are some guidelines about what can be used in the Git documentation:

https://github.com/git/git/blob/master/Documentation/CodingGuidelines

**Comment by anarcat** [comment]
so i guess the question is whether it *does* work with ash or dash. did anyone test that?

switching to /bin/sh can have pretty bad consequences where that shell is not bash, if there are bashisms in the code. this would need to be tested explicitly, IMHO.

**Comment by chriscool** [comment]
On Ubuntu machines /bin/sh is dash and it works. I don't know about ash, but when reviewing PRs I take care about not accepting bashisms.

About testing this, yeah we could use https://www.shellcheck.net/ as it detects bashisms.

**Comment by felipec** [comment]
The code code from Git's test-lib where all the code is supposed to be POSSIX compatible, so there really is no need to discuss which shell to use; it's `/bin/sh`.

``` diff
--- a/sharness.sh
+++ b/sharness.sh
@@ -51,7 +51,7 @@ export SHARNESS_TEST_SRCDIR
 export SHARNESS_ORIG_TERM
 
 # Export SHELL_PATH
-: "${SHELL_PATH:=$SHELL}"
+: "${SHELL_PATH:=/bin/sh}"
 export SHELL_PATH
 
 # if --tee was passed, write the output not only to the terminal, but
```

Git also defaults to `/bin/sh`.

Now, if for some reason you want to use a different shell, just do: `make SHELL_PATH=/bin/zsh test`, and you can be happy knowing that you made everything fail.

However, defaulting to currently running shell is certainly one of the worse choices to make.

**Comment by chriscool** [comment]
See: https://github.com/git/git/blob/master/Documentation/CodingGuidelines#L1-L19 for how Git handles POSIX compatibility.

I tend to agree with @felipec 's patch and plan to merge his merge request (https://github.com/chriscool/sharness/pull/93).

We use https://www.shellcheck.net/ to detect bashisms and avoid potential compatibility isues now by the way.

So I think I will close this issue when merging @felipec 's patch.

**Comment by felipec** [comment]
This can be closed now. My patch (0dddcc9) was merged in 2019.
