### ISSUE TITLE
Line feed regression

### ISSUE THREAD

**Issue by felipec** [chriscool/sharness#92]
Commit 0f191d8 simply says "sharness.sh: remove LF definition". But why?

This commit broke my tests, which do make use of LF.

I was a member of the Git project, that's why I started using sharness. A good practice of the Git project is to **always** explain the reasoning behind each change.

I don't see any reasoning behind this change.

**Comment by chriscool** [comment]
The reason is that I don't think it was used anywhere in the project. Sorry for not having been explicit.

**Comment by chriscool** [comment]
Also it was not a public feature, at least not documented in the API as public, so I thought that no one relied on this.

**Comment by felipec** [comment]
OK. That's a good enough reason; that should have been in the commit message. However in the future I thing such removals should be made with a little more consideration.

I'm gonna close this as now I see why you did it and makes sense.
